# Generated by Django 5.2.8 on 2025-11-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='category_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='dr_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='estb_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='homepage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sggu',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sido',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hpid',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
