# Generated by Django 5.2.8 on 2025-12-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carebridge_db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecordReservationMap",
            fields=[
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="carebridge_db.reservations",
                    ),
                ),
                (
                    "medical_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carebridge_db.medicalrecord",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
            ],
            options={
                "db_table": "medical_record_reservation_map",
            },
        ),
    ]

