# Generated by Django 5.2.8 on 2025-12-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erinfo',
            name='place_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RawReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('review_time', models.DateTimeField(blank=True, null=True)),
                ('unique_hash', models.CharField(max_length=255, unique=True)),
                ('er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_reviews', to='carebridge_db.erinfo')),
            ],
            options={
                'db_table': 'raw_review',
            },
        ),
    ]
