# Generated by Django 5.2.8 on 2025-12-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0002_add_image_url_to_medicalnewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('USER', 'User')], max_length=10),
        ),
    ]
