# Generated by Django 5.2.8 on 2025-11-30 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0002_hospital_category_hospital_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.users'),
        ),
    ]
