# Generated by Django 5.2.8 on 2025-12-02 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0003_alter_doctors_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_newsletter',
            },
        ),
        migrations.AlterField(
            model_name='laborders',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='medicineorders',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='treatmentprocedures',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord'),
        ),
    ]
