# Generated by Django 5.2.8 on 2025-12-02 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0003_alter_doctors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborders',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='medicineorders',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='treatmentprocedures',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord'),
        ),
    ]
