# Generated by Django 5.2.8 on 2025-12-02 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0004_alter_laborders_medical_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erstatus',
            name='er',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='carebridge_db.erinfo'),
        ),
    ]
