# Generated by Django 5.2.8 on 2025-12-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0004_medicalnewsletter_alter_laborders_medical_record_and_more'),
        ('carebridge_db', '0005_alter_erstatus_er'),
    ]

    operations = [
    ]
